-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    inn character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    phone character varying(50) COLLATE pg_catalog."default",
    is_buyer boolean DEFAULT false,
    is_salesman boolean DEFAULT false,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT customers_inn_key UNIQUE (inn)
);

CREATE TABLE IF NOT EXISTS public.materials
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    unit character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT materials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_compositions
(
    order_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 3) NOT NULL,
    price numeric(15, 2) NOT NULL,
    CONSTRAINT order_compositions_pkey PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer NOT NULL,
    order_date date NOT NULL,
    executor_id integer NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prices
(
    id serial NOT NULL,
    product_id character varying(50) COLLATE pg_catalog."default",
    material_id character varying(50) COLLATE pg_catalog."default",
    price numeric(15, 2) NOT NULL,
    effective_date date NOT NULL,
    CONSTRAINT prices_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.productions
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    specification_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    production_date date NOT NULL,
    product_quantity numeric(15, 3) NOT NULL,
    CONSTRAINT productions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    unit character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.specification_compositions
(
    specification_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    material_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    material_quantity numeric(15, 3) NOT NULL,
    CONSTRAINT specification_compositions_pkey PRIMARY KEY (specification_id, material_id)
);

CREATE TABLE IF NOT EXISTS public.specifications
(
    id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    product_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 3) NOT NULL DEFAULT 1,
    description text COLLATE pg_catalog."default",
    CONSTRAINT specifications_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.order_compositions
    ADD CONSTRAINT order_compositions_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_compositions_order
    ON public.order_compositions(order_id);


ALTER TABLE IF EXISTS public.order_compositions
    ADD CONSTRAINT order_compositions_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_orders_customer
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_executor_id_fkey FOREIGN KEY (executor_id)
    REFERENCES public.customers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_orders_executor
    ON public.orders(executor_id);


ALTER TABLE IF EXISTS public.prices
    ADD CONSTRAINT prices_material_id_fkey FOREIGN KEY (material_id)
    REFERENCES public.materials (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_prices_material
    ON public.prices(material_id);


ALTER TABLE IF EXISTS public.prices
    ADD CONSTRAINT prices_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_prices_product
    ON public.prices(product_id);


ALTER TABLE IF EXISTS public.productions
    ADD CONSTRAINT productions_specification_id_fkey FOREIGN KEY (specification_id)
    REFERENCES public.specifications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_productions_specification
    ON public.productions(specification_id);


ALTER TABLE IF EXISTS public.specification_compositions
    ADD CONSTRAINT specification_compositions_material_id_fkey FOREIGN KEY (material_id)
    REFERENCES public.materials (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.specification_compositions
    ADD CONSTRAINT specification_compositions_specification_id_fkey FOREIGN KEY (specification_id)
    REFERENCES public.specifications (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_spec_compositions_spec
    ON public.specification_compositions(specification_id);


ALTER TABLE IF EXISTS public.specifications
    ADD CONSTRAINT specifications_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_specifications_product
    ON public.specifications(product_id);

END;